pipeline {
    agent any
    
    tools {
        // Fait référence au nom 'maven' que tu as configuré (Tâche 4)
        maven 'maven' 
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Cloning repository from GitHub...'
            }
        }
        stage('Build and Test') {
            steps {
                echo 'Building the application and running tests with Maven...'
                sh 'mvn clean install'
            }
        }
        // **********************************************
        // * NOUVELLE ÉTAPE : DEPLOIEMENT *
        // **********************************************
        stage('Deploy') { 
            steps {
                echo 'Deployment stage added. We will configure SSH details next.'
                // C'est ici que nous insérerons le code de connexion SSH
            }
        }
    }
}