pipeline {
    agent any
    
    tools {
        maven 'maven' 
    }
    
    environment {
        DEPLOY_CREDENTIALS = 'ssh_deploy_server' 
        TARGET_HOST = '127.0.0.1' 
        TARGET_USER = 'ELITEBOOK' 
        TARGET_DIR = 'C:/Temp' 
        JAR_FILE = 'jenkins-demo-0.0.1-SNAPSHOT.jar'
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Cloning repository from GitHub...'
            }
        }
        stage('Build and Test') {
            steps {
                echo 'Building the application and running tests with Maven...'
                // ********************************************
                // CORRECTION : sh remplacé par bat
                // ********************************************
                bat 'mvn clean install' 
            }
        }
        stage('Deploy') { 
            steps {
                echo "Copying application to ${TARGET_USER}@${TARGET_HOST}:${TARGET_DIR}"
                
                // Utilisation de sshagent pour déverrouiller les identifiants SSH stockés
                sshagent(credentials: [DEPLOY_CREDENTIALS]) {
                    // ********************************************
                    // CORRECTION : sh remplacé par bat pour la commande scp
                    // ********************************************
                    bat "scp POV-JAVA/target/${JAR_FILE} ${TARGET_USER}@${TARGET_HOST}:${TARGET_DIR}"
                }
                
                echo 'Deployment copy finished.'
            }
        }
    }
}